title: Blog page for testing
author: Balaji R
email: balajiram@cpan.org
description: > # this means to ignore newlines until "baseurl:"
   I like to be a non-social animal and keep to myself. This is my first blog on GitHub.
   
# social links
twitter_username: your-twitter-handle
github_username:  balajirama

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
